apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: container-lab
  source:
    repoURL: git://container-lab-git.git.svc.cluster.local:9418/repo.git
    targetRevision: main
    path: container-lab/k8s/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
