apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/your-org/onprem-go-api
    newName: registry.lab.internal/platform/onprem-go-api
    newTag: dev
patches:
  - target:
      kind: Deployment
      name: go-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: lab

