apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: mac-vmware-lab
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.10.0
    helm:
      valuesObject:
        persistence:
          defaultClassReplicaCount: 3
        defaultSettings:
          defaultReplicaCount: 3
          replicaAutoBalance: best-effort
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

