global:
  domain: argocd.container.local

configs:
  params:
    server.insecure: true

server:
  replicas: 1
  service:
    type: ClusterIP

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

redis-ha:
  enabled: false
