apiVersion: v1
kind: Namespace
metadata:
  name: git
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-lab-git
  namespace: git
  labels:
    app.kubernetes.io/name: container-lab-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: container-lab-git
  template:
    metadata:
      labels:
        app.kubernetes.io/name: container-lab-git
    spec:
      containers:
        - name: git-daemon
          image: localhost:5001/container-lab-git:container
          imagePullPolicy: IfNotPresent
          ports:
            - name: git
              containerPort: 9418
          readinessProbe:
            tcpSocket:
              port: git
            periodSeconds: 2
          livenessProbe:
            tcpSocket:
              port: git
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: container-lab-git
  namespace: git
spec:
  selector:
    app.kubernetes.io/name: container-lab-git
  ports:
    - name: git
      port: 9418
      targetPort: git
