apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../k8s/apps/go-api/base
images:
  - name: ghcr.io/your-org/onprem-go-api
    newName: localhost:5001/onprem-go-api
    newTag: container
patches:
  - target:
      kind: Deployment
      name: go-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: container
